version: '3.8'

services:
  sender:
    build:
      dockerfile: sender.Dockerfile
    deploy:
      replicas: 1
    stdin_open: true
    tty: true
    network_mode: bridge
    volumes: 
      - /Users/minghanchan/Desktop/EL122 - Networks/networksProj/network-emulation/ecgen/logs:/app/logs

  router:
    build:
      dockerfile: router.Dockerfile
      # args:
      #   packet_drop_rate: ${PACKET_DROP_RATE}
    deploy:
      replicas: 20
    network_mode: bridge
    volumes: 
      - /Users/minghanchan/Desktop/EL122 - Networks/networksProj/network-emulation/ecgen/logs:/app/logs

  receiver:
    build:
      dockerfile: receiver.Dockerfile
    deploy:
      replicas: 10
    network_mode: bridge
    volumes:
      - /Users/minghanchan/Desktop/EL122 - Networks/networksProj/network-emulation/ecgen/logs:/app/logs


