
# docker-compose up -d
# docker-compose logs <service-name>

version: '3.8'

services:
  sender:
    build:
      dockerfile: sender.Dockerfile
    deploy:
      replicas: 1
    stdin_open: true
    tty: true
    network_mode: bridge

  router:
    build:
      dockerfile: router.Dockerfile
    deploy:
      replicas: 5
    network_mode: bridge

  receiver:
    build:
      dockerfile: receiver.Dockerfile
    deploy:
      replicas: 15
    network_mode: bridge


