version: '3.8'

services:
  source-node:
    build:
      context: .
      dockerfile: Dockerfile
    # Set the number of desired replicas (containers)
    # You can adjust the `replicas` value as needed
    deploy:
      replicas: 3
    # Optionally, you can set environment variables or other configurations here
